matrix:
  include:
    - language: java
      jdk: openjdk8

      before_script:
        - cd ./backend/
      script:
        - mvn test -B
    
    - language: node_js
      node_js:
        - '8'
    
      addons:
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
    
      before_script:
        - cd ./frontend/

      cache:
        directories:
          - ./node_modules
    
      install:
        - npm install
    
      script:
        - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless
