  
version: "3.7"

services:
    openvidu-server-kms:
        image: openvidu/openvidu-server-kms:latest
        ports:
            - "4443:4443"
        environment:
            OPENVIDU_SECRET: ${OPENVIDU_SECRET}

    openvidu-teaching:
        image: diegomzmn/openviduteaching:latest
        volumes:
            - ${LOCAL_INITIAL_FILE_PATH}:${DOCKER_INITIAL_FILE_PATH}
        ports:
            - "8080:8080"
        environment:
            OPENVIDU_URL: https://${DOMAIN_OR_PUBLIC_IP}:4443/
            OPENVIDU_SECRET: ${OPENVIDU_SECRET}
            INITIAL_DATA_FILE: ${DOCKER_INITIAL_FILE_PATH}