  
version: "3.7"

services:
    openvidu-server-kms:
        image: openvidu/openvidu-server-kms:latest
        ports:
            - "4443:4443"
        environment:
            OPENVIDU_SECRET: ${OPENVIDU_SECRET}

    openvidu-teaching:
        image: diegomzmn/openviduteaching:latest
        volumes:
            - ${LOCAL_INITIAL_FILE_PATH}:${DOCKER_INITIAL_FILE_PATH}
            - ${LOCAL_ASSETS_FOLDER}:${DOCKER_ASSETS_FOLDER}
        ports:
            - "8080:8080"
        environment:
            OPENVIDU_URL: https://${DOMAIN_OR_PUBLIC_IP}:4443/
            OPENVIDU_SECRET: ${OPENVIDU_SECRET}
            INITIAL_DATA_FILE: ${DOCKER_INITIAL_FILE_PATH}
            ASSETS_FOLDER: ${DOCKER_ASSETS_FOLDER}
            OPENVIDU_RECORDING: ${OPENVIDU_RECORDING}
            PRIMARY_R: ${PRIMARY_R}
            PRIMARY_G: ${PRIMARY_G}
            PRIMARY_B: ${PRIMARY_B}
            ACCENT_R: ${ACCENT_R}
            ACCENT_G: ${ACCENT_G}
            ACCENT_B: ${ACCENT_B}
            WARN_R: ${WARN_R}
            WARN_G: ${WARN_G}
            WARN_B: ${WARN_B}
            LIGHT_THEME: ${LIGHT_THEME}